ARG EXPORT_DIR=/export

FROM erikja/bulb:0.1.0 AS acquire-exe
ARG EXPORT_DIR
ARG ARCH=amd64
RUN install -d $EXPORT_DIR
RUN install-pkgs -a $ARCH -r $EXPORT_DIR curl

FROM erikja/bulb:0.1.0 AS build
ARG EXPORT_DIR
ARG ARCH=amd64
RUN install -d $EXPORT_DIR
COPY --from=acquire-exe $EXPORT_DIR/usr/bin/curl /tmp/curl
RUN build-sysroot -m -o $EXPORT_DIR /tmp/curl

FROM scratch
ARG EXPORT_DIR
COPY --from=build $EXPORT_DIR /
ENTRYPOINT ["/usr/bin/curl"]